# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Julia.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1211, 644)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 336, 590))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.splitter)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_2 = QtGui.QLabel(self.splitter_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.splitter_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_7 = QtGui.QSplitter(self.tab)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.label_8 = QtGui.QLabel(self.splitter_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox = QtGui.QComboBox(self.splitter_7)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout.addWidget(self.splitter_7)
        self.splitter_3 = QtGui.QSplitter(self.tab)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.label_4 = QtGui.QLabel(self.splitter_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalSlider = QtGui.QSlider(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider.setMaximum(500)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtGui.QSplitter(self.tab)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.label_3 = QtGui.QLabel(self.splitter_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalSlider_2 = QtGui.QSlider(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_2.setMaximum(500)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtGui.QSplitter(self.tab)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_5 = QtGui.QLabel(self.splitter_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalSlider_3 = QtGui.QSlider(self.splitter_5)
        self.horizontalSlider_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_3.setMinimum(-50)
        self.horizontalSlider_3.setMaximum(50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.verticalLayout.addWidget(self.splitter_5)
        self.splitter_6 = QtGui.QSplitter(self.tab)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.label_6 = QtGui.QLabel(self.splitter_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalSlider_4 = QtGui.QSlider(self.splitter_6)
        self.horizontalSlider_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_4.setMinimum(-50)
        self.horizontalSlider_4.setMaximum(50)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.verticalLayout.addWidget(self.splitter_6)
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter_8 = QtGui.QSplitter(self.tab)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.label_36 = QtGui.QLabel(self.splitter_8)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.spinBox_3 = QtGui.QSpinBox(self.splitter_8)
        self.spinBox_3.setProperty("value", 5)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.spinBox_4 = QtGui.QSpinBox(self.splitter_8)
        self.spinBox_4.setProperty("value", 5)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.verticalLayout.addWidget(self.splitter_8)
        self.splitter_9 = QtGui.QSplitter(self.tab)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.label_37 = QtGui.QLabel(self.splitter_9)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.lineEdit_19 = QtGui.QLineEdit(self.splitter_9)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.verticalLayout.addWidget(self.splitter_9)
        self.splitter_10 = QtGui.QSplitter(self.tab)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_38 = QtGui.QLabel(self.splitter_10)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.lineEdit_20 = QtGui.QLineEdit(self.splitter_10)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.verticalLayout.addWidget(self.splitter_10)
        self.pushButton_6 = QtGui.QPushButton(self.tab)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout.addWidget(self.pushButton_6)
        spacerItem1 = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.splitter.raise_()
        self.splitter_2.raise_()
        self.splitter_3.raise_()
        self.splitter_4.raise_()
        self.splitter_5.raise_()
        self.splitter_6.raise_()
        self.splitter_7.raise_()
        self.progressBar.raise_()
        self.pushButton_3.raise_()
        self.spinBox_4.raise_()
        self.spinBox_3.raise_()
        self.label_36.raise_()
        self.pushButton_6.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_13 = QtGui.QSplitter(self.tab_2)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.label_7 = QtGui.QLabel(self.splitter_13)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBox_2 = QtGui.QComboBox(self.splitter_13)
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout_2.addWidget(self.splitter_13)
        self.splitter_14 = QtGui.QSplitter(self.tab_2)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.label_9 = QtGui.QLabel(self.splitter_14)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spinBox = QtGui.QSpinBox(self.splitter_14)
        self.spinBox.setMaximumSize(QtCore.QSize(50, 20))
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_2.addWidget(self.splitter_14)
        self.splitter_15 = QtGui.QSplitter(self.tab_2)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName(_fromUtf8("splitter_15"))
        self.label_10 = QtGui.QLabel(self.splitter_15)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.spinBox_2 = QtGui.QSpinBox(self.splitter_15)
        self.spinBox_2.setMaximumSize(QtCore.QSize(50, 20))
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setSingleStep(1)
        self.spinBox_2.setProperty("value", 100)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout_2.addWidget(self.splitter_15)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 3, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout.addWidget(self.lineEdit_8, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.splitter_11 = QtGui.QSplitter(self.tab_2)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName(_fromUtf8("splitter_11"))
        self.label_11 = QtGui.QLabel(self.splitter_11)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_9 = QtGui.QLineEdit(self.splitter_11)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout_2.addWidget(self.splitter_11)
        self.splitter_12 = QtGui.QSplitter(self.tab_2)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.label_17 = QtGui.QLabel(self.splitter_12)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_10 = QtGui.QLineEdit(self.splitter_12)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_2.addWidget(self.splitter_12)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.progressBar_2 = QtGui.QProgressBar(self.tab_2)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.verticalLayout_2.addWidget(self.progressBar_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setMinimumSize(QtCore.QSize(100, 0))
        self.label_18.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_3.addWidget(self.label_18)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setMinimumSize(QtCore.QSize(50, 0))
        self.label_19.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_2.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setMinimumSize(QtCore.QSize(50, 0))
        self.label_20.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setMinimumSize(QtCore.QSize(50, 0))
        self.label_21.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_2.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 2, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setMinimumSize(QtCore.QSize(50, 0))
        self.label_28.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 3, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_2.addWidget(self.lineEdit_16, 3, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setMinimumSize(QtCore.QSize(50, 0))
        self.label_23.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_2.addWidget(self.lineEdit_15, 4, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setMinimumSize(QtCore.QSize(50, 0))
        self.label_22.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 5, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_2.addWidget(self.lineEdit_14, 5, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 5, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setMinimumSize(QtCore.QSize(50, 0))
        self.label_31.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 6, 0, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_2.addWidget(self.lineEdit_17, 6, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 6, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setMinimumSize(QtCore.QSize(50, 0))
        self.label_33.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 7, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_2.addWidget(self.lineEdit_18, 7, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 7, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.label_35 = QtGui.QLabel(self.tab_3)
        self.label_35.setMinimumSize(QtCore.QSize(100, 0))
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_3.addWidget(self.label_35)
        self.textEdit = QtGui.QTextEdit(self.tab_3)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.textEdit)
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.progressBar_3 = QtGui.QProgressBar(self.tab_3)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.verticalLayout_3.addWidget(self.progressBar_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(350, 20, 581, 571))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.textEdit_2 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(940, 20, 261, 471))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.tabWidget.raise_()
        self.widget.raise_()
        self.textEdit_2.raise_()
        self.progressBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_model = QtGui.QAction(MainWindow)
        self.actionCreate_model.setObjectName(_fromUtf8("actionCreate_model"))
        self.actionSimulate_model = QtGui.QAction(MainWindow)
        self.actionSimulate_model.setObjectName(_fromUtf8("actionSimulate_model"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Julia", None))
        self.pushButton_2.setText(_translate("MainWindow", "Import Low Energy CT", None))
        self.pushButton.setText(_translate("MainWindow", "Import High Energy CT", None))
        self.label.setText(_translate("MainWindow", "Core diameter (mm)", None))
        self.lineEdit.setText(_translate("MainWindow", "100", None))
        self.label_2.setText(_translate("MainWindow", "Selected Core diameter (mm)", None))
        self.lineEdit_2.setText(_translate("MainWindow", "50", None))
        self.label_8.setText(_translate("MainWindow", "Orientation", None))
        self.label_4.setText(_translate("MainWindow", "Cropping Top (mm)", None))
        self.label_3.setText(_translate("MainWindow", "Cropping Bottom (mm)", None))
        self.label_5.setText(_translate("MainWindow", "Offset X (mm)", None))
        self.label_6.setText(_translate("MainWindow", "Offset Y (mm)", None))
        self.pushButton_3.setText(_translate("MainWindow", "Create Upscaled model", None))
        self.label_36.setText(_translate("MainWindow", "Dimensions (XY,Z)", None))
        self.label_37.setText(_translate("MainWindow", "Porosity", None))
        self.lineEdit_19.setText(_translate("MainWindow", "0.2", None))
        self.label_38.setText(_translate("MainWindow", "Permeability", None))
        self.lineEdit_20.setText(_translate("MainWindow", "200", None))
        self.pushButton_6.setText(_translate("MainWindow", "Create Dummy Model", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Core Model", None))
        self.label_7.setText(_translate("MainWindow", "Experiment type", None))
        self.label_9.setText(_translate("MainWindow", "Number of cycles", None))
        self.label_10.setText(_translate("MainWindow", "Cycle time", None))
        self.label_12.setText(_translate("MainWindow", "Oil", None))
        self.label_13.setText(_translate("MainWindow", "Water", None))
        self.label_14.setText(_translate("MainWindow", "Density", None))
        self.lineEdit_3.setText(_translate("MainWindow", "780", None))
        self.lineEdit_4.setText(_translate("MainWindow", "1000", None))
        self.label_15.setText(_translate("MainWindow", "Viscosity", None))
        self.lineEdit_5.setText(_translate("MainWindow", "1.2", None))
        self.lineEdit_6.setText(_translate("MainWindow", "0.36", None))
        self.label_16.setText(_translate("MainWindow", "Comp", None))
        self.lineEdit_7.setText(_translate("MainWindow", "0", None))
        self.lineEdit_8.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "Swir", None))
        self.lineEdit_9.setText(_translate("MainWindow", "0.3", None))
        self.label_17.setText(_translate("MainWindow", "water rate", None))
        self.lineEdit_10.setText(_translate("MainWindow", "12", None))
        self.pushButton_4.setText(_translate("MainWindow", "Run Simulation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Simulation", None))
        self.label_18.setText(_translate("MainWindow", "Oil/Water", None))
        self.label_19.setText(_translate("MainWindow", "Lo", None))
        self.lineEdit_11.setText(_translate("MainWindow", "1", None))
        self.label_24.setText(_translate("MainWindow", "0", None))
        self.label_20.setText(_translate("MainWindow", "Eo", None))
        self.lineEdit_12.setText(_translate("MainWindow", "2", None))
        self.label_25.setText(_translate("MainWindow", "0", None))
        self.label_21.setText(_translate("MainWindow", "To", None))
        self.lineEdit_13.setText(_translate("MainWindow", "2", None))
        self.label_26.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", "Lw", None))
        self.lineEdit_16.setText(_translate("MainWindow", "1", None))
        self.label_27.setText(_translate("MainWindow", "0", None))
        self.label_23.setText(_translate("MainWindow", "Ew", None))
        self.lineEdit_15.setText(_translate("MainWindow", "2", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", "Tw", None))
        self.lineEdit_14.setText(_translate("MainWindow", "2", None))
        self.label_29.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "Sorw", None))
        self.lineEdit_17.setText(_translate("MainWindow", "0.2", None))
        self.label_32.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", "Krw", None))
        self.lineEdit_18.setText(_translate("MainWindow", "0.8", None))
        self.label_34.setText(_translate("MainWindow", "0", None))
        self.label_35.setText(_translate("MainWindow", "Historical data", None))
        self.pushButton_5.setText(_translate("MainWindow", "Fit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Parametrization", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionCreate_model.setText(_translate("MainWindow", "Create model", None))
        self.actionSimulate_model.setText(_translate("MainWindow", "Simulate model", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

