<eclipse>
<message date="12/10/2015" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="12/10/2015" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="12/10/2015" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     769220 BYTES                                                        
</message>
<message date="12/10/2015" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="12/10/2015" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="12/10/2015" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1034                                          
</message>
<warning date="12/10/2015" time="0.00000000000000">
 NSTACK =     50   WHICH EXCEEDS THE                                     
 LARGEST VALUE OF LITMAX IN THE DECK,  WHICH IS     25  .                
 THE EXCESS MEMORY REQUESTED BY NSTACK WILL NOT BE USED                  
 AND WILL REDUCE PERFORMANCE AND MAY CAUSE MEMORY OVERFLOW.              
 NSTACK WILL BE REDUCED                                                  
 TO THE LARGEST LITMAX VALUE IN THE DECK.                                
 SET OPTIONS(256)=1 TO STOP THIS FROM HAPPENING.                         
</warning>
<message date="12/10/2015" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       2013 KBYTES                                                       
</message>
<message date="12/10/2015" time="0.00000000000000">
    62244 CHARACTER VARIABLES USED                                       
</message>
<message date="12/10/2015" time="0.00000000000000">
 OPENING WELL PROD1    AT TIME      0.00   HOURS                         
 CONTROLLED BY BOTTOM HOLE PRESSURE                                      
</message>
<warning date="12/10/2015" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL INJ1                            
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS    6803.  ATMOSA               
</warning>
<message date="12/10/2015" time="0.00000000000000">
 OPENING WELL INJ1     AT TIME      0.00   HOURS                         
 CONTROLLED BY WATER RATE                                                
</message>
<problem date="12/10/2015" time="0.00000000000000">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - BUT TIME STEP                                 
 ACCEPTED BECAUSE IT IS TOO SMALL TO CHOP.                               
 USE KEYWORD MESSOPTS TO MODIFY THE SEVERITY CODE FOR                    
 MESSAGES REPORTING TIME STEPS FORCED TO BE ACCEPTED.                    
</problem>
<message date="12/10/2015" time="0.01700000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<problem date="12/10/2015" time="0.01700000000000">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - BUT TIME STEP                                 
 ACCEPTED BECAUSE IT IS TOO SMALL TO CHOP.                               
 USE KEYWORD MESSOPTS TO MODIFY THE SEVERITY CODE FOR                    
 MESSAGES REPORTING TIME STEPS FORCED TO BE ACCEPTED.                    
</problem>
<message date="12/10/2015" time="0.03400000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.05100000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.06800000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.08500000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.10200000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.11900000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.13600000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.15300000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/10/2015" time="0.17000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
</eclipse>
